version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 19132:19132/udp
      - 19133:19133/udp
      - 443:443/tcp
    volumes:
      - ./worlds:/server/worlds
